flowchart LR
  subgraph Auth
    U[Users]
    R[Roles]
    UR[UserRoles]
    LH[LoginHistories]
  end
  subgraph People
    P[Patients]
    E[Employees]
    D[Doctors]
    S[Specialties]
  end
  subgraph Scheduling
    Ro[Rooms]
    DS[DoctorSchedules]
    A[Appointments]
  end
  subgraph Medical
    MR[MedicalRecords]
    EX[Examinations]
    SV[Services]
    SO[ServiceOrders]
  end
  subgraph Pharmacy
    MC[MedicineCategories]
    M[Medicines]
    PR[Prescriptions]
    PD[PrescriptionDetails]
    IT[InventoryTransactions]
  end

  U --> UR
  R --> UR
  U --> LH
  U --> E
  E --> D
  S --> D
  P --> A
  D --> A
  Ro --> A
  D --> DS
  Ro --> DS
  A --> EX
  MR --> EX
  D --> EX
  EX --> SO
  SV --> SO
  EX --> PR
  D --> PR
  PR --> PD
  M --> PD
  M --> IT
  U --> IT
  P --> MR
  U --> A
  U --> PR
  U --> IT
  U --> DS
